apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{- .Values.airflow.prefix -}}worker"
spec:
  replicas: {{ .Values.celery.num_workers }}
  template:
    metadata:
      labels:
        app: airflow
        tier: worker
    spec:
      restartPolicy: Always
      containers:
        - name: "{{- .Values.airflow.prefix -}}worker"
          imagePullPolicy: {{ .Values.airflow.image_pull_policy}}
          image: "{{ .Values.airflow.image }}"
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: dags-data
              mountPath: {{ .Values.airflow.dag_path }}
          {{- end }}
          # volumes:
          #     - /localpath/to/dags:/usr/local/airflow/dags
          envFrom:
            - configMapRef:
                name: "{{- .Values.airflow.prefix -}}airflow-env"
          args: ["worker"]
          {{- if .Values.airflow.airflow_cfg.enable }}
          volumeMounts:
            - mountPath: /usr/local/airflow-cm/
              name: "{{ .Values.airflow.prefix -}}airflow-cfg"
          command: ["bash", "/usr/local/airflow-cm/bootstrap.sh"]
          {{- end }}
      volumes:
        - name: dags-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
              claimName: {{ .Values.persistence.existingClaim | default (include "airflow.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.airflow.airflow_cfg.enable }}
        - name: "{{ .Values.airflow.prefix -}}airflow-cfg"
          configMap:
            name: "{{ .Values.airflow.prefix -}}airflow.cfg"
        {{ end -}}
